In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [102]:
data  = pd.read_csv("data.csv")

In [103]:
data.head()

,expedition_id,member_id,peak_id,peak_name,year,season,sex,age,citizenship,expedition_role,...,highpoint_metres,success,solo,oxygen_used,died,death_cause,death_height_metres,injured,injury_type,injury_height_metres
0,AMAD78301,AMAD78301-01,AMAD,Ama Dablam,1978,Autumn,M,40.0,France,Leader,...,NaN,False,False,False,False,NaN,NaN,False,NaN,NaN
1,AMAD78301,AMAD78301-02,AMAD,Ama Dablam,1978,Autumn,M,41.0,France,Deputy Leader,...,6000.0,False,False,False,False,NaN,NaN,False,NaN,NaN
2,AMAD78301,AMAD78301-03,AMAD,Ama Dablam,1978,Autumn,M,27.0,France,Climber,...,NaN,False,False,False,False,NaN,NaN,False,NaN,NaN
3,AMAD78301,AMAD78301-04,AMAD,Ama Dablam,1978,Autumn,M,40.0,France,Exp Doctor,...,6000.0,False,False,False,False,NaN,NaN,False,NaN,NaN
4,AMAD78301,AMAD78301-05,AMAD,Ama Dablam,1978,Autumn,M,34.0,France,Climber,...,NaN,False,False,False,False,NaN,NaN,False,NaN,NaN

In [104]:
data.tail()

,expedition_id,member_id,peak_id,peak_name,year,season,sex,age,citizenship,expedition_role,...,highpoint_metres,success,solo,oxygen_used,died,death_cause,death_height_metres,injured,injury_type,injury_height_metres
76514,PUTH19101,PUTH19101-07,PUTH,Putha Hiunchuli,2019,Spring,M,44.0,Nepal,H-A Worker,...,6350.0,False,False,False,False,NaN,NaN,False,NaN,NaN
76515,RATC19101,RATC19101-01,RATC,Ratna Chuli,2019,Spring,M,55.0,Romania,Leader,...,6600.0,False,False,False,False,NaN,NaN,False,NaN,NaN
76516,SANK19101,SANK19101-01,SANK,Sano Kailash,2019,Spring,M,56.0,Austria,Leader,...,6452.0,True,False,False,False,NaN,NaN,False,NaN,NaN
76517,SANK19101,SANK19101-02,SANK,Sano Kailash,2019,Spring,F,57.0,Austria,Climber,...,5700.0,False,False,False,False,NaN,NaN,False,NaN,NaN
76518,SANK19101,SANK19101-03,SANK,Sano Kailash,2019,Spring,M,41.0,Nepal,H-A Worker,...,6452.0,True,False,False,False,NaN,NaN,False,NaN,NaN

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76519 entries, 0 to 76518
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   expedition_id         76519 non-null  object
 1   member_id             76519 non-null  object
 2   peak_id               76519 non-null  object
 3   peak_name             76504 non-null  object
 4   year                  76519 non-null  int64
 5   season                76519 non-null  object
 6   sex                   76517 non-null  object
 7   age                   73022 non-null  float64
 8   citizenship           76509 non-null  object
 9   expedition_role       76498 non-null  object
 10  hired                 76519 non-null  bool
 11  highpoint_metres      54686 non-null  float64
 12  success               76519 non-null  bool
 13  solo                  76519 non-null  bool
 14  oxygen_used           76519 non-null  bool
 15  died                  76519 non-null  bool
 16  death_cause           1106 non-null   object
 17  death_height_metres   1068 non-null   float64
 18  injured               76519 non-null  bool
 19  injury_type           1712 non-null   object
 20  injury_height_metres  1009 non-null   float64
dtypes: bool(6), float64(4), int64(1), object(10)
memory usage: 9.2+ MB

In [106]:
data = data.drop(columns=['expedition_id', 'member_id', 'peak_id', 'death_cause','injured', 'injury_type', 'injury_height_metres', 'sex', 'citizenship', 'expedition_role', 'highpoint_metres', 'solo', 'death_height_metres'])

In [107]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76519 entries, 0 to 76518
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peak_name    76504 non-null  object
 1   year         76519 non-null  int64
 2   season       76519 non-null  object
 3   age          73022 non-null  float64
 4   hired        76519 non-null  bool
 5   success      76519 non-null  bool
 6   oxygen_used  76519 non-null  bool
 7   died         76519 non-null  bool
dtypes: bool(4), float64(1), int64(1), object(2)
memory usage: 2.6+ MB

In [108]:
data

             peak_name  year  season   age  hired  success  oxygen_used   died
0           Ama Dablam  1978  Autumn  40.0  False    False        False  False
1           Ama Dablam  1978  Autumn  41.0  False    False        False  False
2           Ama Dablam  1978  Autumn  27.0  False    False        False  False
3           Ama Dablam  1978  Autumn  40.0  False    False        False  False
4           Ama Dablam  1978  Autumn  34.0  False    False        False  False
...                ...   ...     ...   ...    ...      ...          ...    ...
76514  Putha Hiunchuli  2019  Spring  44.0   True    False        False  False
76515      Ratna Chuli  2019  Spring  55.0  False    False        False  False
76516     Sano Kailash  2019  Spring  56.0  False     True        False  False
76517     Sano Kailash  2019  Spring  57.0  False    False        False  False
76518     Sano Kailash  2019  Spring  41.0   True     True        False  False

[76519 rows x 8 columns]

In [109]:
data = data.dropna(subset= ['peak_name'])

In [110]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76504 entries, 0 to 76518
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peak_name    76504 non-null  object
 1   year         76504 non-null  int64
 2   season       76504 non-null  object
 3   age          73007 non-null  float64
 4   hired        76504 non-null  bool
 5   success      76504 non-null  bool
 6   oxygen_used  76504 non-null  bool
 7   died         76504 non-null  bool
dtypes: bool(4), float64(1), int64(1), object(2)
memory usage: 3.2+ MB

In [111]:
median_age = data['age'].median()

In [115]:
data['age'] = data['age'].fillna(median_age)

C:\Users\shahi\AppData\Local\Temp\ipykernel_7600\3797857117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['age'] = data['age'].fillna(median_age)

In [116]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76504 entries, 0 to 76518
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peak_name    76504 non-null  object
 1   year         76504 non-null  int64
 2   season       76504 non-null  object
 3   age          76504 non-null  float64
 4   hired        76504 non-null  bool
 5   success      76504 non-null  bool
 6   oxygen_used  76504 non-null  bool
 7   died         76504 non-null  bool
dtypes: bool(4), float64(1), int64(1), object(2)
memory usage: 3.2+ MB

In [117]:
data

             peak_name  year  season   age  hired  success  oxygen_used   died
0           Ama Dablam  1978  Autumn  40.0  False    False        False  False
1           Ama Dablam  1978  Autumn  41.0  False    False        False  False
2           Ama Dablam  1978  Autumn  27.0  False    False        False  False
3           Ama Dablam  1978  Autumn  40.0  False    False        False  False
4           Ama Dablam  1978  Autumn  34.0  False    False        False  False
...                ...   ...     ...   ...    ...      ...          ...    ...
76514  Putha Hiunchuli  2019  Spring  44.0   True    False        False  False
76515      Ratna Chuli  2019  Spring  55.0  False    False        False  False
76516     Sano Kailash  2019  Spring  56.0  False     True        False  False
76517     Sano Kailash  2019  Spring  57.0  False    False        False  False
76518     Sano Kailash  2019  Spring  41.0   True     True        False  False

[76504 rows x 8 columns]

In [118]:
data['age'] = data['age'].astype(int)

C:\Users\shahi\AppData\Local\Temp\ipykernel_7600\3403544981.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['age'] = data['age'].astype(int)

In [119]:
data

             peak_name  year  season  age  hired  success  oxygen_used   died
0           Ama Dablam  1978  Autumn   40  False    False        False  False
1           Ama Dablam  1978  Autumn   41  False    False        False  False
2           Ama Dablam  1978  Autumn   27  False    False        False  False
3           Ama Dablam  1978  Autumn   40  False    False        False  False
4           Ama Dablam  1978  Autumn   34  False    False        False  False
...                ...   ...     ...  ...    ...      ...          ...    ...
76514  Putha Hiunchuli  2019  Spring   44   True    False        False  False
76515      Ratna Chuli  2019  Spring   55  False    False        False  False
76516     Sano Kailash  2019  Spring   56  False     True        False  False
76517     Sano Kailash  2019  Spring   57  False    False        False  False
76518     Sano Kailash  2019  Spring   41   True     True        False  False

[76504 rows x 8 columns]

In [120]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 76504 entries, 0 to 76518
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   peak_name    76504 non-null  object
 1   year         76504 non-null  int64
 2   season       76504 non-null  object
 3   age          76504 non-null  int64
 4   hired        76504 non-null  bool
 5   success      76504 non-null  bool
 6   oxygen_used  76504 non-null  bool
 7   died         76504 non-null  bool
dtypes: bool(4), int64(2), object(2)
memory usage: 3.2+ MB

In [123]:
data.to_csv('cleaned_data', index=4)